title: 'Bitcoin Core PR Review Club'

author:
  name: 'Bitcoin Core PR Review Club hosts'

menu:
- {name: 'Home', url: ''}
- {name: 'Meetings', url: 'meetings/'}
- {name: 'Code of Conduct', url: 'code-of-conduct/'}
